<?php
/**
 * ProductOnlineStatusApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ProductsV1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\ProductsV1;

use EzzeSiftuz\ProductsV1\Configuration;
use EzzeSiftuz\ProductsV1\ApiException;
use EzzeSiftuz\ProductsV1\ObjectSerializer;

/**
 * ProductOnlineStatusApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\ProductsV1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductOnlineStatusApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getOnlineStatus
     *
     * Read the online status of your product variations. The total number of results could be limited by specifying query parameters. Generally the resulting online status values will be paginated. The default page length is 100 online status entries per response, also the page size limit. The links specified in the result can be used to page through the total result space..
     *
     */
    public function testGetOnlineStatus()
    {
    }

    /**
     * Test case for getVariationOnlineStatus
     *
     * Read the online status of a single product variation..
     *
     */
    public function testGetVariationOnlineStatus()
    {
    }

    /**
     * Test case for updateOnlineStatus
     *
     * Update the online status of your product variations and get a process-id to query results.
     *
     */
    public function testUpdateOnlineStatus()
    {
    }
}
